Feature/book model
dafeys/book_store pull request #1
Opened 2023-10-13 19:48 UTC by dafeys

2023-10-29 20:58 UTC, loqimean requested changes

2023-10-29 20:58 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +    }
винеси в окремий файл все, порозділяй

2023-10-29 20:58 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +    }
*файли

2023-10-29 20:58 UTC, loqimean commented on app/views/books/_form.html.erb
> +
```suggestion
```

2023-10-29 20:58 UTC, loqimean commented on app/views/books/_form.html.erb
> +<%= simple_form_for @book do |form| %>
а де шлях, куди ти форму посилаєш?

2023-10-29 20:58 UTC, loqimean commented on app/views/books/index.html.erb
> +
```suggestion
```

2023-10-29 20:58 UTC, loqimean commented on app/views/books/index.html.erb
> +  <div id="books" class="min-w-full">
тобі точно треба ця айдішка тут?

2023-10-29 20:58 UTC, loqimean commented on app/views/layouts/_flashes.html.erb
> +<% if flash.any? %>
нема сенсу з цієї перевірки

2023-10-29 20:58 UTC, loqimean commented on config/routes.rb
> +  root "books#index"
рут зазвичай зверху знаходиться

2023-10-29 20:58 UTC, loqimean commented on db/migrate/20231013074202_create_books.rb
> +      t.text :description
теее ж питання); у тебе може бути рекорд без полів?

2023-10-29 20:58 UTC, loqimean commented on db/migrate/20231013194214_change_null_values.rb
> +    change_column_null :books, :isbn, false
те ж саме), роби ролбек і міняй ту міграцію, не обовʼязково створювати нову в межах одного ПР-а

2023-10-29 20:58 UTC, loqimean commented on db/seeds.rb
> +FactoryBot.create_list(:book, 10)
де нова строка в кінці, а також навіщо нова строка на початку?))

2023-10-29 20:58 UTC, loqimean commented on spec/models/book_spec.rb
> +    it { is_expected.to allow_value("").for(:description) }
це шуда-матчерс тестує теж, передай відповідні опшини

2023-10-29 20:58 UTC, loqimean commented on spec/requests/books_spec.rb
> +  let(:invalid_attributes) { { title: "" }  }
можеш створити трейт і тут атрібютс_фор заюзати

2023-10-29 20:58 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
де тестування на пристуність рекорду, який ти маєш рендерити?))

2023-10-29 20:58 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
так само і в інших місцях, де він рендериться

2023-10-29 20:58 UTC, loqimean commented on spec/requests/books_spec.rb
> +
```suggestion
```

2023-10-29 20:58 UTC, loqimean commented on spec/requests/books_spec.rb
> +        end.to change(Book, :count).by(0)
not_to change

2023-10-30 09:44 UTC, dafeys commented on app/assets/stylesheets/application.tailwind.css
> +    }
done

2023-10-30 09:44 UTC, dafeys commented on app/views/books/_form.html.erb
> +
done

2023-10-30 09:44 UTC, dafeys commented on app/views/books/index.html.erb
> +
done

2023-10-30 09:44 UTC, dafeys commented on app/views/books/index.html.erb
> +  <div id="books" class="min-w-full">
done

2023-10-30 09:45 UTC, dafeys commented on app/views/layouts/_flashes.html.erb
> +<% if flash.any? %>
done

2023-10-30 09:46 UTC, dafeys commented on config/routes.rb
> +  root "books#index"
right

2023-10-30 09:47 UTC, dafeys commented on db/seeds.rb
> +FactoryBot.create_list(:book, 10)
done

2023-10-30 09:49 UTC, dafeys commented on spec/requests/books_spec.rb
> +  let(:invalid_attributes) { { title: "" }  }
thnks for solution, done

2023-10-30 16:13 UTC, dafeys commented on spec/requests/books_spec.rb
> +        end.to change(Book, :count).by(0)
done

2023-10-30 16:40 UTC, dafeys commented on spec/requests/books_spec.rb
> +
done

2023-10-30 18:15 UTC, dafeys commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
done

2023-10-30 18:47 UTC, dafeys commented on spec/models/book_spec.rb
> +    it { is_expected.to allow_value("").for(:description) }
allow_blank?

2023-10-30 18:54 UTC, dafeys commented on db/migrate/20231013194214_change_null_values.rb
> +    change_column_null :books, :isbn, false
got it!

2023-10-30 18:55 UTC, dafeys commented on db/migrate/20231013074202_create_books.rb
> +      t.text :description
fixed

2023-10-30 23:35 UTC, dafeys commented on app/views/books/_form.html.erb
> +<%= simple_form_for @book do |form| %>
fixed now

2023-11-01 07:56 UTC, loqimean requested changes

2023-11-01 07:56 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +@import "tailwindcss/utilities";
```suggestion
@import "tailwindcss/utilities";

```

2023-11-01 07:56 UTC, loqimean commented on spec/models/book_spec.rb
> +      book.attributes = valid_attributes
що це таке?))

2023-11-01 07:56 UTC, loqimean commented on spec/models/book_spec.rb
> +      book.attributes = valid_attributes
якщо на те пішло, то навіщо тобі оце аж так дуюлюватися, відразу в тесті роби білд і перевіряй на валідність, навіщо ця зайва робота

2023-11-01 07:56 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response.body).to include("Books")
ну це не обовєязково

2023-11-01 07:56 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response.body).to include(book.title)
а де перевірка статусу?))

2023-11-01 07:56 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response.body).to include("New book")
те ж питання

2023-11-01 07:56 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response.body).to include(book.title)
теж

2023-11-01 12:46 UTC, dafeys commented on app/assets/stylesheets/application.tailwind.css
> +@import "tailwindcss/utilities";
done

2023-11-01 12:46 UTC, dafeys commented on spec/requests/books_spec.rb
> +      expect(response.body).to include("Books")
прибрав

2023-11-01 12:47 UTC, dafeys commented on spec/models/book_spec.rb
> +      book.attributes = valid_attributes
прибрав

2023-11-01 12:47 UTC, dafeys commented on spec/requests/books_spec.rb
> +      expect(response.body).to include(book.title)
дійсно, додав

2023-11-01 12:47 UTC, dafeys commented on spec/requests/books_spec.rb
> +      expect(response.body).to include("New book")
+

2023-11-01 12:47 UTC, dafeys commented on spec/requests/books_spec.rb
> +      expect(response.body).to include(book.title)
+

2023-11-02 07:58 UTC, loqimean requested changes

2023-11-02 07:58 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +@import "tailwindcss/utilities";
не дон)

2023-11-02 07:58 UTC, loqimean commented on spec/models/book_spec.rb
> +    it { is_expected.not_to allow_value("12345678901234").for(:isbn) }
ну перший і наступні два тести роблять абсолютно те ж саме)

2023-11-02 07:58 UTC, loqimean commented on spec/models/book_spec.rb
> +    it { is_expected.to validate_length_of(:author).is_at_most(50) }
обʼєднай це

2023-11-02 07:58 UTC, loqimean commented on spec/models/book_spec.rb
> +    it { is_expected.to validate_length_of(:title).is_at_most(50) }
це теж

2023-11-02 07:58 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response.body).to include(book.title)
але тепер через це у тебе флакі тест), ми на мітингу про це говорили)

2023-11-02 09:22 UTC, dafeys commented on spec/models/book_spec.rb
> +    it { is_expected.not_to allow_value("12345678901234").for(:isbn) }
Прибрав

2023-11-02 09:24 UTC, dafeys commented on spec/models/book_spec.rb
> +    it { is_expected.to validate_length_of(:author).is_at_most(50) }
Об'єднав

2023-11-02 09:24 UTC, dafeys commented on spec/models/book_spec.rb
> +    it { is_expected.to validate_length_of(:title).is_at_most(50) }
Об'єднав

2023-11-02 09:47 UTC, dafeys commented on spec/requests/books_spec.rb
> +      expect(response.body).to include(book.title)
Додав ШТМЛ ескейпінг

2023-11-02 09:58 UTC, dafeys commented on app/assets/stylesheets/application.tailwind.css
> +@import "tailwindcss/utilities";
Пустий рядок додав

2023-11-05 11:36 UTC, loqimean requested changes

2023-11-05 11:36 UTC, loqimean commented on spec/models/book_spec.rb
> +
```suggestion
```

2023-11-05 11:36 UTC, loqimean commented on spec/requests/books_spec.rb
> +  let(:invalid_attributes) { FactoryBot.attributes_for(:book, :without_title) }
Клас не треба передавати

2023-11-05 15:06 UTC, dafeys commented on spec/requests/books_spec.rb
> +  let(:invalid_attributes) { FactoryBot.attributes_for(:book, :without_title) }
Fixed. переробив конфіг, тепер не передаю

2023-11-05 15:07 UTC, dafeys commented on spec/models/book_spec.rb
> +
Прибрав пусті рядки

2023-11-05 18:24 UTC, loqimean approved these changes

2023-11-05 20:41 UTC, merged