Active storage
dafeys/book_store pull request #3
Opened 2023-11-06 09:03 UTC by dafeys

2023-11-06 21:28 UTC, loqimean commented on app/assets/stylesheets/components/show.css
> +    @apply  items-center gap-2 px-6 py-3 font-sans text-xs font-bold text-center text-emerald-500 uppercase align-middle transition-all rounded-lg select-none hover:bg-emerald-500/10 active:bg-emeral
```suggestion
    @apply items-center gap-2 px-6 py-3 font-sans text-xs font-bold text-center text-emerald-500 uppercase align-middle transition-all rounded-lg select-none hover:bg-emerald-500/10 active:bg-emerald-500/30 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none
```

2023-11-06 21:28 UTC, loqimean commented on app/assets/stylesheets/components/show.css
> +    @apply  mt-4 text-center;
```suggestion
    @apply mt-4 text-center;
```

2023-11-06 21:55 UTC, dafeys commented on app/assets/stylesheets/components/show.css
> +    @apply  items-center gap-2 px-6 py-3 font-sans text-xs font-bold text-center text-emerald-500 uppercase align-middle transition-all rounded-lg select-none hover:bg-emerald-500/10 active:bg-emeral
fixed

2023-11-06 21:55 UTC, dafeys commented on app/assets/stylesheets/components/show.css
> +    @apply  mt-4 text-center;
fixed

2023-11-07 07:25 UTC, loqimean commented on app/views/books/show.html.erb
> +        <%= image_tag "http://via.placeholder.com/640x360", class: "object-cover w-full h-full" %>
бачу це посилання часто повторюється, може б то його в який хелпер перенести? і взагалі, там можна зробити таку картинку дефолтною

2023-11-07 07:25 UTC, loqimean commented on app/views/books/show.html.erb
> +        <%= image_tag "http://via.placeholder.com/640x360", class: "object-cover w-full h-full" %>
і взагалі код повторюється, я думаю то на рівні моделі тре було би вирішити

2023-11-07 07:25 UTC, loqimean commented on spec/models/book_spec.rb
> +      file = fixture_file_upload(Rails.root.join("spec", "fixtures", "test_cover.jpg"), "image/jpg")
ну а `let` для чого придумали?))

2023-11-07 07:25 UTC, loqimean commented on spec/models/book_spec.rb
> +      file = fixture_file_upload(Rails.root.join("spec", "fixtures", "dummy.pdf"), "application/pdf")
те ж питання)

2023-11-07 07:25 UTC, loqimean commented on spec/models/book_spec.rb
> +      file = fixture_file_upload(Rails.root.join("spec", "fixtures", "dummy.pdf"), "application/pdf")
та і в цих тестах ти робиш рівно те ж саме, що і шуда матчерс робить, та і що реілс-тіма зробила - тестуєш аттачінг

2023-11-07 07:25 UTC, loqimean commented on app/views/books/_book.html.erb
> +  <% end %>
другий раз код повторюється

2023-11-11 14:24 UTC, dafeys commented on app/views/books/show.html.erb
> +        <%= image_tag "http://via.placeholder.com/640x360", class: "object-cover w-full h-full" %>
Переніс логіку відображення обкладинки в хелпер. Дефолтну обкладинку не робив, бо подумав що це непотрібні операції для кожної книги що створюється без обкладинки і ці дані будуть дублюватися

2023-11-11 14:24 UTC, dafeys commented on app/views/books/_book.html.erb
> +  <% end %>
переніс в хелпер

2023-11-11 14:34 UTC, dafeys commented on spec/models/book_spec.rb
> +      file = fixture_file_upload(Rails.root.join("spec", "fixtures", "dummy.pdf"), "application/pdf")
Прибрав тести на додавання атачменту до вже створеної книги

2023-11-11 14:34 UTC, dafeys commented on spec/models/book_spec.rb
> +      file = fixture_file_upload(Rails.root.join("spec", "fixtures", "test_cover.jpg"), "image/jpg")
Прибрав тести на додавання атачменту до вже створеної книги

2023-11-12 13:39 UTC, loqimean requested changes

2023-11-12 13:39 UTC, loqimean commented on app/helpers/application_helper.rb
> +      image_tag "book_cover.jpg", class: "book-img"
винеси спільний знаменник за дужки))

2023-11-13 16:18 UTC, dafeys commented on app/helpers/application_helper.rb
> +      image_tag "book_cover.jpg", class: "book-img"
трішки оптимізував

2023-11-15 16:44 UTC, loqimean approved these changes

2023-11-15 16:44 UTC, loqimean commented on app/helpers/application_helper.rb
> +    image = book.book_cover.attached? ? book.book_cover : "book_cover.jpg"
```suggestion
    image = book.book_cover.attached? ? book.book_cover : "book_cover.jpg"

```

2023-11-15 17:40 UTC, merged