Elasticsearch
dafeys/book_store pull request #4
Opened 2023-11-21 23:34 UTC by dafeys

Add elasticsearch with chewy gem

![image](https://github.com/dafeys/book_store/assets/36037839/a42d3ae2-8cbc-4d30-88fb-bf7514176b3a)

2023-11-28 07:42 UTC, loqimean requested changes

2023-11-28 07:42 UTC, loqimean commented on app/controllers/books_controller.rb
> +    query = params[:search][:query]
ну а якщо сьорч поверне ніл?

2023-11-28 07:42 UTC, loqimean commented on app/controllers/books_controller.rb
> +      redirect_to(request.referer || books_path) and return
для цього є окремий метод у рельсі), `redirect_back_path` і там є параметер тобі потрібний

2023-11-28 07:42 UTC, loqimean commented on app/models/book.rb
> +  update_index("books") { self if saved_change_to_title? || saved_change_to_author?}
не тре ці перевірки

2023-11-28 07:42 UTC, loqimean commented on app/services/book_search.rb
> +    books.sort_by { |book| book_ids.index(book.id) }
а це навіщо?) давайте без цього, це не оптимально і так ніхто не робить

2023-11-28 07:42 UTC, loqimean commented on config/application.rb
> +require "chewy"
а це навіщо?

2023-11-28 07:42 UTC, loqimean commented on config/environment.rb
> +BooksIndex.import(force: true)
це точно треба?

2023-11-28 07:42 UTC, loqimean commented on spec/services/book_search_spec.rb
> +    BooksIndex.import!
не тре цього

2023-11-30 23:27 UTC, dafeys commented on app/controllers/books_controller.rb
> +    query = params[:search][:query]
Переробив логіку

2023-11-30 23:28 UTC, dafeys commented on app/controllers/books_controller.rb
> +      redirect_to(request.referer || books_path) and return
цікавенно, заюзав його

2023-11-30 23:31 UTC, dafeys commented on app/models/book.rb
> +  update_index("books") { self if saved_change_to_title? || saved_change_to_author?}
Хотів позбутися оновлення індексу при зміні description чи ISBN, бо вони у мене не індексуються, а індекс через їх зміну переоновлювався
Прибрав перевірки

2023-11-30 23:33 UTC, dafeys commented on app/services/book_search.rb
> +    books.sort_by { |book| book_ids.index(book.id) }
Дійсно, якась нісенітниця. Переробив.

2023-11-30 23:33 UTC, dafeys commented on config/application.rb
> +require "chewy"
Перевірив, не треба

2023-11-30 23:34 UTC, dafeys commented on spec/services/book_search_spec.rb
> +    BooksIndex.import!
Прибрав, працює без цього

2023-11-30 23:40 UTC, dafeys commented on config/environment.rb
> +BooksIndex.import(force: true)
прибрав

2024-11-23 16:23 UTC, merged